# Generated by Django 5.0.6 on 2024-07-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todos.family'),
        ),
    ]
