# Generated by Django 5.0.6 on 2024-10-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_task_description_en_task_description_es_task_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Tarea realizada'),
        ),
    ]
